/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package isobit;

import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static io.restassured.RestAssured.given;
import static org.hamcrest.CoreMatchers.is;

@QuarkusTest
public class LibraryTest {
    @Test 
    public void testSomeLibraryMethod() {
        
    }
}
